M48
; DRILL file {KiCad 9.0.1} date 2025-10-29T09:40:07+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-29T09:40:07+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.311
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.089
%
G90
G05
T1
X108.8Y-137.65
X151.4Y-137.65
T2
X104.7Y-141.5
X155.5Y-141.5
M30
